### ISSUE TITLE
typed client generation only generates one client when there are multiple contracts in a single file

### ISSUE THREAD

**Issue by iskysun96** [algorandfoundation/algokit-python-template#35]
### Subject of the issue

When you have multiple smart contracts defined in one file, algokit project run build doesn't generate the typed client for the second app

![image](https://github.com/algorandfoundation/algokit-python-template/assets/52557585/c1f1ff07-811c-4301-bc7f-3a062ecf4884)
![image](https://github.com/algorandfoundation/algokit-python-template/assets/52557585/d911fef5-d427-42dc-8176-f8ce78bbe38e)

### Expected behaviour

client is generated for both smart contracts

### Actual behaviour

only generates the first contract

**Comment by aorumbayev** [comment]
in case of python template, above pr fixes the issue + further simplifies the helpers folder 
In case of beaker and given its being deprecated, only similar changes on helpers folder are propagated.
