### ISSUE TITLE
Missing method in Python testing context

### ISSUE THREAD

**Issue by cusma** [algorandfoundation/algokit-python-template#42]
### Subject of the issue

The AlgoKit init make use of:

```python
dummy_input = context.any.string(length=10)
```

In the default `_test.py` file.

The `any.string` method is missing in `context`, it should be replaced by `any_string`.

### Steps to reproduce

1. Init a new Python Smart Contract project with AlgoKit
2. Run tests

**Comment by aorumbayev** [comment]
@cusma you are on an older version of the unit testing package, latest template uses the prerelease version which consolidates values generators under any property. Make sure to update algorand-python-tesitng to at least https://github.com/algorandfoundation/algokit-python-template/blob/c6ad5fb3b36f710b32039cd4a40f4761d7f49b21/examples/production_python/pyproject.toml#L13
