### ISSUE TITLE
Make "Use this template" button available

### ISSUE THREAD

**Issue by iskysun96** [algorandfoundation/algokit-python-template#62]
## Problem
https://github.com/algorandfoundation/algokit-cli/blob/4b4310cbd931537fe4a93f8439a8c0f439367183/docs/tutorials/algokit-template.md?plain=1
This doc mentions clicking on Use this template->Create a new repository on [algokit-python-template](https://github.com/algorandfoundation/algokit-python-template) but the "Use this template" button does not show up. 

## Solution

enable "template repository" https://github.com/orgs/community/discussions/130131

**Comment by robdmoore** [comment]
I can see it?

![image](https://github.com/user-attachments/assets/c32e2c45-f961-43ec-9505-2d88439078a0)
